/*
 ============================================================================
   Web Solution Project, ID SW Development Department, LG ELECTRONICS INC., SEOUL, KOREA
   Copyright(c) 2021 by LG Electronics Inc.

 ============================================================================
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var c,b=[];!(c=a.next()).done;)b.push(c.value);return b};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(a){var c=function(){};c.prototype=a;return new c};
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){if(a==Array.prototype||a==Object.prototype)return a;a[c]=b.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var b=a[c];if(b&&b.Math==Math)return b}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,c){var b=$jscomp.propertyToPolyfillSymbol[c];if(null==b)return a[c];b=a[b];return void 0!==b?b:a[c]};
$jscomp.polyfill=function(a,c,b,d){c&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,c,b,d):$jscomp.polyfillUnisolated(a,c,b,d))};$jscomp.polyfillUnisolated=function(a,c,b,d){b=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var f=a[d];if(!(f in b))return;b=b[f]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})};
$jscomp.polyfillIsolated=function(a,c,b,d){var f=a.split(".");a=1===f.length;d=f[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var l=0;l<f.length-1;l++){var n=f[l];if(!(n in d))return;d=d[n]}f=f[f.length-1];b=$jscomp.IS_SYMBOL_NATIVE&&"es6"===b?d[f]:null;c=c(b);null!=c&&(a?$jscomp.defineProperty($jscomp.polyfills,f,{configurable:!0,writable:!0,value:c}):c!==b&&(void 0===$jscomp.propertyToPolyfillSymbol[f]&&(b=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[f]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(f):$jscomp.POLYFILL_PREFIX+b+"$"+f),$jscomp.defineProperty(d,$jscomp.propertyToPolyfillSymbol[f],{configurable:!0,writable:!0,value:c})))};
$jscomp.getConstructImplementation=function(){function a(){function b(){}new b;Reflect.construct(b,[],function(){});return new b instanceof b}if($jscomp.TRUST_ES6_POLYFILLS&&"undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var c=Reflect.construct;return function(b,d,f){b=c(b,d);f&&Reflect.setPrototypeOf(b,f.prototype);return b}}return function(b,d,f){void 0===f&&(f=b);f=$jscomp.objectCreate(f.prototype||Object.prototype);return Function.prototype.apply.call(b,f,d)||
f}};$jscomp.construct={valueOf:$jscomp.getConstructImplementation}.valueOf();$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},c={};try{return c.__proto__=a,c.a}catch(b){}return!1};$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,c){a.__proto__=c;if(a.__proto__!==c)throw new TypeError(a+" is not extensible");return a}:null;
$jscomp.inherits=function(a,c){a.prototype=$jscomp.objectCreate(c.prototype);a.prototype.constructor=a;if($jscomp.setPrototypeOf){var b=$jscomp.setPrototypeOf;b(a,c)}else for(b in c)if("prototype"!=b)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(c,b);d&&Object.defineProperty(a,b,d)}else a[b]=c[b];a.superClass_=c.prototype};var extIDCAPSecure,extRegisterIDCAPCloseHandler,extDisableIdcapConsoleLog,extWebWorker,isSubscribeParam,retry_count,idcap;
if(void 0===idcap)if("object"===typeof window)(function(){function a(e){1==idcap.isLogEnabled&&(e=1024<e.length?e.substring(0,1024):e,!0!==extWebWorker&&console.log(e))}function c(e,g){if(!0!==extWebWorker){var h="",m=document.createEvent("HTMLEvents");a(q("event received, ",g));m.initEvent(e,!0,!1);for(h in g)g.hasOwnProperty(h)&&(m[h]=g[h]);document.dispatchEvent(m)}}idcap={API_VERSION:"$IDCAP_JS_EXTENSION_VERSION",isRemoteInitialize:!1,isRemote:!1,remote_ip:"",isLogEnabled:!1,isMaxCount:4};var b=
0,d=[{command_id:"0",param_text:'{"command_id" : "0", "command" : "notify_sdk_version","parameters":{"idcap_js_extension_version" : "$IDCAP_JS_EXTENSION_VERSION"}}'}],f=[{command:"0",param_text:'{"command" : "0", "command" : "notify_sdk_version", "parameters":{"idcap_js_extension_version" : "$IDCAP_JS_EXTENSION_VERSION"}}'}],l=null,n=!1,v=!1,p=!1,A=null,w=null,E=null,B=!1,q=null,C=!1,z=!1,D=0,x="127.0.0.1";!0!==idcap.isLogEnabled?!0!==extWebWorker&&console.log("ID -  console log is disabled"):!0!==
extWebWorker&&console.log("ID -  console log is enabled");a("check external value : extDisableIdcapConsoleLog = "+extDisableIdcapConsoleLog+", extIDCAPSecure = "+extIDCAPSecure+", extRegisterIDCAPCloseHandler = "+extRegisterIDCAPCloseHandler);B=function(){var e=navigator.userAgent;e.match(/Windows/);e.match(/Macintosh/);e.match(/Mac OS X/);var g=e.match(/Web0S/),h=e.match(/SmartTV/),m=e.match(/WebAppManager/);a("UA = '"+e+"'");return g||h||m?(z=!1,idcap.isRemote=!1):z=idcap.isRemote=!0}();q=function(e,
g){var h="";var m=[],r="";for(h in g)g.hasOwnProperty(h)&&m.push(h);m.sort();for(h=0;h<m.length;h+=1){var u=h,k=m,t="",y="";var F=k[u];try{t=g[F],y=typeof t}catch(G){t="<unknown value>",y="unknown"}"function"===y?t="{/*function*/}":"object"===y?t=q("",t):"string"===y&&(t='"'+t+'"');r+='"'+F+'" : '+t;u<k.length-1&&(r+=", ")}return e+"{"+r+"}"};A=function(){a("initialize_idcap_websocket");v?a("websocket : connection is in progress"):(v=!0,0==z?!0!==extIDCAPSecure?(a("default idcap connection"),l=new WebSocket("ws://127.0.0.1:8153/hcap_command")):
(a("secure idcap connection"),l=new WebSocket("wss://localhost:8154/idcap_command")):(a("remote connection"),l="https:"===location.protocol?new WebSocket("wss://"+x+":8154/idcap_command"):new WebSocket("ws://"+x+":8153/idcap_command")),l.onopen=function(){a("websocket : onopen");v=!1;n=!0;setTimeout(w,5)},l.onmessage=function(e){e=JSON.parse(e.data);var g=e.command_id,h=e.command,m=e.result;a("ws.onmessage : "+JSON.stringify(e));if("event"===g)"debug_event_received"===h?(e.enable_log?!0!==extWebWorker&&
console.log("idcap console log is enabled"):!0!==extWebWorker&&console.log("idcap console log is disabled"),extDisableIdcapConsoleLog=!e.enable_log):c(h,e);else{if(0<d.length&&d[0].command_id===g){a(q("command_id = "+g+" received, ",e));if(m){if(d[0].onSuccess)try{d[0].onSuccess(e)}catch(k){a(q("exception : onSuccess : "+k))}}else if(d[0].onFailure)try{d[0].onFailure(e)}catch(k){a(q("exception : onFailure : "+k))}d.splice(0,1)}else{var r=0,u=!1;f.forEach(function(k){null!==k&&void 0!==k.command&&
k.command===h&&(r=f.indexOf(k),u=!0)});if(u){if(f[r].onSuccess)try{f[r].onSuccess(e)}catch(k){a(q("exception : onSuccess : "+k))}}else a(q("invalid response from server ",e))}p=!1;w()}},l.onclose=function(){a("websocket : onclose");p=n=v=!1;D+=1;a("retry-count",D);!z&&D<idcap.isMaxCount?setTimeout(w,50):a("Max retry - stop websocket connection try")},"onbeforeunload"===extRegisterIDCAPCloseHandler?window.onbeforeunload=function(){a("close idcap websocket in onbeforeunload handler");l.onclose=function(){};
l.close()}:"onunload"===extRegisterIDCAPCloseHandler&&(window.onunload=function(){a("close idcap websocket in onunload handler");l.onclose=function(){};l.close()}))};w=function(){a("start_cmd_loop");if(!p){p=!0;if(n){if(0<d.length){a("webSocket sending");a(q("command_id = "+d[0].command_id+" sent, ",JSON.parse(d[0].param_text)));l.send(d[0].param_text);return}}else A();p=!1}};E=function(e,g){if(null===e||""===e||void 0===e)a("[ERROR] Command should not be null.");else if(!1===e.toLowerCase().startsWith("idcap://"))a("[ERROR] wrong IDCAP command.");
else if(Array.isArray(g))a("[ERROR] Command Parameter Error. param is Array type or not defined.");else{B&&a("[ERROR] IDCAP is unavailable on this browser.");b=1024<b?0:b+1;var h=b.toString(),m="";g.command_id=h;g.command=e;m=JSON.stringify(g,null);a("param_text : "+m);for(name in g)"subscribe"===name&&g.hasOwnProperty("subscribe")&&!0===g.subscribe&&(C=!0);if(C)f.forEach(function(k){null!==k&&void 0!==k.command&&k.command===g.command?a("already registered. : "+e):f[f.length]={command:e,param_text:m,
onSuccess:g.onSuccess,onFailure:g.onFailure}}),C=!1;else{var r=0,u=!1;f.forEach(function(k){null!==k&&void 0!==k.command&&k.command===g.command&&(r=f.indexOf(k),u=!0)});u?f.splice(r,1):!1}d[d.length]={command_id:h,param_text:m,onSuccess:g.onSuccess,onFailure:g.onFailure};a(q("command_id = "+h+" added, ",d[d.length-1]));w()}};B||setTimeout(w,200);idcap.remoteInitialize=function(e){a("remoteInitialize");x=e;a("remote = "+x);idcap.remote_ip=x;A();idcap.isRemoteInitialize=!0};idcap.remoteFinalize=function(){a("remoteFinalize");
l.close();l=null;idcap.remote_ip="";idcap.isRemoteInitialize=!1};idcap.request={};idcap.request=function(e,g){e=e.toLowerCase();E(e,g)}})();else{var ev=require("events").EventEmitter,IDCAP=function(a){var c=ev.call(this)||this;c.service=a;c.service.Request=function(b,d){var f=b;"/"!=f.charAt(f.length-1)&&(f+="/");f+=d.method;var l={};!0===d.hasOwnProperty("parameters")&&(l=d.parameters);var n={},v=function(p){idcapLog("res : "+JSON.stringify(p));!0===p.payload.returnValue?(n=p.payload,d.onSuccess(n)):
(n.returnValue=!1,n.errorCode=p.payload.errorCode,n.errorText=p.payload.errorText,d.onFailure(n))};c.service&&c.service.call(f,l,v)};c.subsForEvents=c.service.subscribe("luna://com.webos.service.idcapmw.mwcommand/getAllEvents",{subscribe:!0});c.subsForEvents.on("response",function(b){b=b.payload;if("event"===b.command_id)c.on_event_received(b.command,b)});return c};$jscomp.inherits(IDCAP,ev);IDCAP.prototype.on_event_received=function(a,c){this.emit(a,c)};IDCAP.prototype.request=function(a,c){null===
a||""===a||void 0===a?idcapLog("[ERROR] Command should not be null."):Array.isArray(c)||void 0===c?idcapLog("[ERROR] Command Parameter Error. param is Array type or not defined."):c.onSuccess&&"function"===typeof c.onSuccess?c.onFailure&&"function"===typeof c.onFailure?this.service.Request("luna://com.webos.service.idcapmw.mwcommand",{method:"/callIDCAP",parameters:{command:a,parameters:c.parameters},onSuccess:function(b){b.result?(delete b.returnValue,delete b.result,delete b.command_id,c.onSuccess(b)):
(delete b.returnValue,delete b.result,delete b.command_id,c.onFailure(b))},onFailure:function(b){delete b.returnValue;delete b.result;delete b.command_id;c.onFailure(b)}}):idcapLog("[ERROR] onFailure callback Error. onFailure is not function."):idcapLog("[ERROR] onSuccess callback Error. onSuccess is not function.")};module.exports=IDCAP};